# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'Default'

variables:
- group: Github-Packages
- name: solution
  value: 'IconLib\IconLib.sln'
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'
- name: buildMachine
  value: '$(Agent.MachineName)'
- name: buildUser
  value: '$(Build.QueuedBy)'

steps:
- powershell: 'Write-Host ("##vso[task.setvariable variable=MSBuildEmitSolution;]0")'
  displayName: 'Ensure MSBuildEmitSolution is not set'

- task: NuGetToolInstaller@0
  inputs:
    versionSpec: 5.4.0

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'config'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    clean: true
    msbuildArgs: '/t:IconLib:Pack /p:PushPackage=false /p:PackageOutputPath="$(Build.ArtifactStagingDirectory)" /p:BuildUser="$(buildUser)" /p:BuildMachine="$(buildMachine)" /p:AssemblyVersionSuffix="-ci"'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'

- script: ECHO $(GITHUB_TEST) from $(Build.ArtifactStagingDirectory) to $(GITHUB_PACKAGES)
  displayName: Push Nuget Packages to $(GITHUB_PACKAGES) $(GITHUB_TEST)
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)
    GITHUB_PACKAGES: $(GITHUB_PACKAGES)
    PACKAGES_DIR: $(Build.ArtifactStagingDirectory)

- task: CopyFiles@2
  displayName: Create nuget publish config
  inputs:
    sourceFolder: $(Build.SourcesDirectory)\IconLib
    contents: 'nuget.publish.config'
    targetFolder: $(Agent.TempDirectory)

- script: nuget.exe sources Add -NonInteractive -Name github -Source "https://nuget.pkg.github.com/%GITHUB_OWNER%/index.json" -Username "%GITHUB_USERNAME%" -Password "%GITHUB_TOKEN%" -ConfigFile $(Agent.TempDirectory)\nuget.publish.config
  displayName: Add github package source
  env:
    GITHUB_OWNER: $(GITHUB_OWNER)
    GITHUB_USERNAME: $(GITHUB_USERNAME)
    GITHUB_TOKEN: $(GITHUB_TOKEN)

- script: nuget push "%PACKAGES_DIR%/*.nupkg" -Source "https://nuget.pkg.github.com/%GITHUB_OWNER%/index.json" -ConfigFile $(Agent.TempDirectory)\nuget.publish.config
  displayName: Push Nuget Packages to $(GITHUB_PACKAGES)
  env:
    GITHUB_OWNER: $(GITHUB_OWNER)
    PACKAGES_DIR: $(Build.ArtifactStagingDirectory)